Repository whagan/custom_addons, pull requests merged in 2020-10, with the labels that each got.

#17 Update README.md
  README.md
Labels: enhancement

#18 Clic-32 Employee Performance Reports views
  custom_reports/models/__init__.py
  custom_reports/models/custom_report.py
  custom_reports/models/employee_performance.py
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/employee_performance_views.xml
Labels: enhancement

#21 CLIC-33 Contacts Report
  custom_reports/__manifest__.py
  custom_reports/views/contact_report_view.xml
  custom_reports/views/custom_reports_views.xml
Labels: enhancement

#22 CLIC-28 Fix View Button
  custom_reports/demo/demo.xml
  custom_reports/models/custom_report.py
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
Labels: bug

#23 Clic 03 email market models
  custom_reports/__manifest__.py
  custom_reports/demo/demo.xml
  custom_reports/demo/email_marketing_demo.xml
  custom_reports/demo/test.txt
  custom_reports/models/__init__.py
  custom_reports/models/email_marketing.py
  custom_reports/security/ir.model.access.csv
  custom_reports/static/img/binder_clips.png
  custom_reports/static/img/calendar.png
  custom_reports/static/img/clipboard.png
  custom_reports/static/img/lamp.png
  custom_reports/static/img/mouse_pad.png
  custom_reports/static/img/note_pad.png
  custom_reports/static/img/paper_clips.png
  custom_reports/static/img/pencil_sharpener.png
  custom_reports/static/img/pens.png
  custom_reports/static/img/scissors.png
  custom_reports/static/img/stapler.png
  custom_reports/static/img/tape_dispenser.png
  custom_reports/static/newsletters/August.png
  custom_reports/static/newsletters/July.png
  custom_reports/static/newsletters/October.png
  custom_reports/static/newsletters/September.png
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/employee_performance_views.xml
Labels: enhancement

#24 Clic 2 sales by location
  README.md
  custom_reports/__manifest__.py
  custom_reports/demo/demo.xml
  custom_reports/models/__init__.py
  custom_reports/models/custom_report.py
  custom_reports/models/sales_by_location.py
  custom_reports/security/ir.model.access.csv
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/sales_by_location_reports_views.xml
Labels: bug, enhancement
