Repository whagan/custom_addons, pull requests merged in 2020-11, with the labels that each got.

#31 Clic 8 inventory statistics
  custom_reports/__manifest__.py
  custom_reports/demo/demo.xml
  custom_reports/demo/email_marketing_demo.xml
  custom_reports/demo/employee_performance_demo.xml
  custom_reports/demo/test.txt
  custom_reports/models/__init__.py
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/models/restock.py
  custom_reports/security/ir.model.access.csv
  custom_reports/static/img/email_marketing/newsletters/August.png
  custom_reports/static/img/email_marketing/newsletters/July.png
  custom_reports/static/img/email_marketing/newsletters/October.png
  custom_reports/static/img/email_marketing/newsletters/September.png
  custom_reports/static/img/email_marketing/products/binder_clips.png
  custom_reports/static/img/email_marketing/products/calendar.png
  custom_reports/static/img/email_marketing/products/clipboard.png
  custom_reports/static/img/email_marketing/products/lamp.png
  custom_reports/static/img/email_marketing/products/mouse_pad.png
  custom_reports/static/img/email_marketing/products/note_pad.png
  custom_reports/static/img/email_marketing/products/paper_clips.png
  custom_reports/static/img/email_marketing/products/pencil_sharpener.png
  custom_reports/static/img/email_marketing/products/pens.png
  custom_reports/static/img/email_marketing/products/scissors.png
  custom_reports/static/img/email_marketing/products/stapler.png
  custom_reports/static/img/email_marketing/products/tape_dispenser.png
  custom_reports/static/img/employee_performance/hr/emp_01.jpeg
  custom_reports/static/img/employee_performance/hr/emp_02.jpg
  custom_reports/static/img/employee_performance/hr/emp_03.jpg
  custom_reports/static/img/employee_performance/hr/emp_04.jpg
  custom_reports/static/img/employee_performance/hr/emp_05.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_01.jpeg
  custom_reports/static/img/employee_performance/res_partner/emp_02.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_03.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_04.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_05.jpg
  custom_reports/static/img/employee_performance/res_user/emp_01.jpeg
  custom_reports/static/img/employee_performance/res_user/emp_02.jpg
  custom_reports/static/img/employee_performance/res_user/emp_03.jpg
  custom_reports/static/img/employee_performance/res_user/emp_04.jpg
  custom_reports/static/img/employee_performance/res_user/emp_05.jpg
  custom_reports/static/src/js/custom_reports_controller.js
  custom_reports/static/src/js/custom_reports_model.js
  custom_reports/static/src/js/custom_reports_renderer.js
  custom_reports/static/src/js/custom_reports_view.js
  custom_reports/static/src/js/email_marketing_graph.js
  custom_reports/static/src/js/employee_performance_graph.js
  custom_reports/static/src/js/ribbons.js
  custom_reports/static/src/scss/employee_performance_graph.scss
  custom_reports/static/src/xml/email_marketing_graph.xml
  custom_reports/static/src/xml/employee_performance_graph.xml
  custom_reports/static/src/xml/ribbon.xml
  custom_reports/views/assets.xml
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/restock_report_view.xml
Labels: enhancement

#32 Clic 34 emp perform graph
  custom_reports/__manifest__.py
  custom_reports/demo/email_marketing_demo.xml
  custom_reports/demo/employee_performance_demo.xml
  custom_reports/demo/test.txt
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/static/img/email_marketing/newsletters/August.png
  custom_reports/static/img/email_marketing/newsletters/July.png
  custom_reports/static/img/email_marketing/newsletters/October.png
  custom_reports/static/img/email_marketing/newsletters/September.png
  custom_reports/static/img/email_marketing/products/binder_clips.png
  custom_reports/static/img/email_marketing/products/calendar.png
  custom_reports/static/img/email_marketing/products/clipboard.png
  custom_reports/static/img/email_marketing/products/lamp.png
  custom_reports/static/img/email_marketing/products/mouse_pad.png
  custom_reports/static/img/email_marketing/products/note_pad.png
  custom_reports/static/img/email_marketing/products/paper_clips.png
  custom_reports/static/img/email_marketing/products/pencil_sharpener.png
  custom_reports/static/img/email_marketing/products/pens.png
  custom_reports/static/img/email_marketing/products/scissors.png
  custom_reports/static/img/email_marketing/products/stapler.png
  custom_reports/static/img/email_marketing/products/tape_dispenser.png
  custom_reports/static/img/employee_performance/hr/emp_01.jpeg
  custom_reports/static/img/employee_performance/hr/emp_02.jpg
  custom_reports/static/img/employee_performance/hr/emp_03.jpg
  custom_reports/static/img/employee_performance/hr/emp_04.jpg
  custom_reports/static/img/employee_performance/hr/emp_05.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_01.jpeg
  custom_reports/static/img/employee_performance/res_partner/emp_02.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_03.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_04.jpg
  custom_reports/static/img/employee_performance/res_partner/emp_05.jpg
  custom_reports/static/img/employee_performance/res_user/emp_01.jpeg
  custom_reports/static/img/employee_performance/res_user/emp_02.jpg
  custom_reports/static/img/employee_performance/res_user/emp_03.jpg
  custom_reports/static/img/employee_performance/res_user/emp_04.jpg
  custom_reports/static/img/employee_performance/res_user/emp_05.jpg
  custom_reports/static/src/js/custom_reports_controller.js
  custom_reports/static/src/js/custom_reports_model.js
  custom_reports/static/src/js/custom_reports_renderer.js
  custom_reports/static/src/js/custom_reports_view.js
  custom_reports/static/src/js/email_marketing_graph.js
  custom_reports/static/src/js/employee_performance_graph.js
  custom_reports/static/src/js/ribbons.js
  custom_reports/static/src/scss/employee_performance_graph.scss
  custom_reports/static/src/xml/email_marketing_graph.xml
  custom_reports/static/src/xml/employee_performance_graph.xml
  custom_reports/static/src/xml/ribbon.xml
  custom_reports/views/assets.xml
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
Labels: enhancement

#33 02b fixing sales by location
  custom_reports/demo/demo.xml
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/sales_by_location_reports_views.xml
Labels: enhancement

#44 Clic 40 sales by company update
  custom_reports/__manifest__.py
  custom_reports/demo/demo.xml
  custom_reports/models/__init__.py
  custom_reports/models/sales_by_company.py
  custom_reports/security/ir.model.access.csv
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/sales_by_company_reports_views.xml
Labels: documentation, enhancement

#46 Clic 43 email market update sales delta
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/static/src/js/email_marketing_graph.js
  custom_reports/static/src/js/employee_performance_graph.js
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
Labels: bug

#48 CLIC-39 report title
  custom_reports/models/sales_by_company.py
  custom_reports/models/sales_statistics.py
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/sales_by_company_reports_views.xml
  custom_reports/views/sales_statistics_reports_views.xml
Labels: enhancement

#47 CLIC-38 Form View Notebook visibility
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/sales_by_company_reports_views.xml
  custom_reports/views/sales_statistics_reports_views.xml
Labels: enhancement

#45 Clic 35 sale by company report graph
  custom_reports/__manifest__.py
  custom_reports/models/sales_by_company.py
  custom_reports/static/src/js/sales_by_company_graph.js
  custom_reports/static/src/xml/sales_by_company_graph.xml
  custom_reports/views/assets.xml
  custom_reports/views/sales_by_company_reports_views.xml
Labels: enhancement

#50 CLIC-37 Employee Performance Stuck
  custom_reports/models/employee_performance.py
  custom_reports/static/src/js/employee_performance_graph.js
Labels: bug

#49 CLIC-36 Fix Boolean Datetime Issues
  custom_reports/models/employee_performance.py
  custom_reports/models/sales_by_company.py
  custom_reports/models/sales_statistics.py
Labels: bug

#52 CLIC 43 Custom Reports Form View record name
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/models/restock.py
  custom_reports/models/sales_by_company.py
  custom_reports/models/sales_statistics.py
  custom_reports/views/email_marketing_reports_views.xml
Labels: enhancement

#54 CLIC-44 Order Reports Alphabetically
  custom_reports/demo/demo.xml
  custom_reports/views/custom_reports_views.xml
Labels: enhancement

#57 Clic 46 sales statistics graph
  custom_reports/__manifest__.py
  custom_reports/models/sales_statistics.py
  custom_reports/static/src/js/sales_statistics_graph.js
  custom_reports/static/src/js/traffic_statistic_graph.js
  custom_reports/static/src/xml/sale_statistics_graph.xml
  custom_reports/views/sales_statistics_reports_views.xml
Labels: enhancement

#61 Clic 42 widget bug
  README.md
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/models/restock.py
  custom_reports/models/sales_by_company.py
  custom_reports/models/sales_statistics.py
  custom_reports/models/traffic_statistics.py
  custom_reports/views/restock_report_view.xml
Labels: enhancement

#68 Clic 48 final presentation
  custom_reports/__manifest__.py
  custom_reports/demo/custom_report_demo.xml
  custom_reports/demo/employee_performance_demo.xml
  custom_reports/demo/sales_by_company_demo.xml
  custom_reports/demo/traffic_statistic_demo.xml
  custom_reports/models/custom_report.py
  custom_reports/models/restock.py
  custom_reports/models/sales_statistics.py
  custom_reports/models/traffic_statistics.py
  custom_reports/static/img/employee_performance/products/large-purchases.jpg
  custom_reports/static/img/employee_performance/products/medium-purchases.jpeg
  custom_reports/static/img/sales_company/large-purchases.jpg
  custom_reports/static/img/sales_company/medium-purchases.jpeg
  custom_reports/static/src/js/graphs/email_marketing_graph.js
  custom_reports/static/src/js/graphs/employee_performance_graph.js
  custom_reports/static/src/js/graphs/ribbons.js
  custom_reports/static/src/js/graphs/sales_by_company_graph.js
  custom_reports/static/src/js/graphs/sales_statistic_graph.js
  custom_reports/static/src/js/graphs/sales_statistics_graph.js
  custom_reports/static/src/js/graphs/traffic_statistic_graph.js
  custom_reports/static/src/js/views/custom_reports/custom_reports_list_controller.js
  custom_reports/static/src/js/views/custom_reports/custom_reports_list_renderer.js
  custom_reports/static/src/js/views/custom_reports/custom_reports_list_view.js
  custom_reports/static/src/js/views/sub_reports/sub_reports_list_controller.js
  custom_reports/static/src/js/views/sub_reports/sub_reports_list_renderer.js
  custom_reports/static/src/js/views/sub_reports/sub_reports_list_view.js
  custom_reports/static/src/scss/employee_performance_graph.scss
  custom_reports/views/assets.xml
  custom_reports/views/custom_reports_views.xml
  custom_reports/views/email_marketing_reports_views.xml
  custom_reports/views/employee_performance_reports_views.xml
  custom_reports/views/restock_report_view.xml
  custom_reports/views/sales_by_company_reports_views.xml
  custom_reports/views/sales_statistics_reports_views.xml
  custom_reports/views/traffic_statistics_reports_views.xml
Labels: enhancement

#69 Clic 50 add more comments
  README.md
  custom_reports/models/custom_report.py
  custom_reports/models/email_marketing.py
  custom_reports/models/employee_performance.py
  custom_reports/models/restock.py
  custom_reports/models/sales_by_company.py
  custom_reports/models/sales_statistics.py
  custom_reports/models/traffic_statistics.py
  custom_reports/security/security.xml
  custom_reports/static/src/js/graphs/email_marketing_graph.js
  custom_reports/static/src/js/graphs/employee_performance_graph.js
  custom_reports/static/src/js/graphs/ribbons.js
  custom_reports/static/src/js/graphs/sales_by_company_graph.js
  custom_reports/static/src/js/graphs/sales_statistics_graph.js
  custom_reports/static/src/js/graphs/traffic_statistic_graph.js
  custom_reports/static/src/scss/custom_reports_view.scss
  custom_reports/views/restock_report_view.xml
Labels: documentation

#70 CLIC-51 fix email marketing
  custom_reports/models/email_marketing.py
Labels: bug
